-- MySQL Script generated by MySQL Workbench
-- 02/22/17 23:36:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sanjosep_ventas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sanjosep_ventas` ;

-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`transaccion_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`transaccion_venta` (
  `no_ticket` INT(20) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `total` FLOAT(10,4) NOT NULL,
  `estatus` VARCHAR(4) NOT NULL,
  `usuario_modifica` VARCHAR(20) NULL,
  `fecha_modificacion` DATETIME NULL,
  `tienda` INT(4) NOT NULL,
  PRIMARY KEY (`no_ticket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`transaccion_venta_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`transaccion_venta_det` (
  `no_ticket` INT(20) NOT NULL,
  `upc` VARCHAR(15) NULL,
  `sku` VARCHAR(10) NOT NULL,
  `piezas` FLOAT(10,4) NOT NULL,
  `precio` FLOAT(10,4) NOT NULL,
  `fecha_creacio` DATE NULL,
  `Usuario_cracion` VARCHAR(20) NULL,
  PRIMARY KEY (`no_ticket`),
  CONSTRAINT `fk_transaccion_venta_det_transaccion_venta`
    FOREIGN KEY (`no_ticket`)
    REFERENCES `sanjosep_ventas`.`transaccion_venta` (`no_ticket`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`pagos` (
  `tipo_pago` INT(4) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`tipo_pago_trans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`tipo_pago_trans` (
  `no_ticket` INT(20) NOT NULL,
  `tipo_pago` INT(4) NOT NULL,
  `total_pago` FLOAT(10,4) NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(20) NULL,
  PRIMARY KEY (`no_ticket`),
  INDEX `fk_tipo_pago_tipo_pago1_idx` (`tipo_pago` ASC),
  CONSTRAINT `fk_tipo_pago_transaccion_venta1`
    FOREIGN KEY (`no_ticket`)
    REFERENCES `sanjosep_ventas`.`transaccion_venta` (`no_ticket`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tipo_pago_tipo_pago1`
    FOREIGN KEY (`tipo_pago`)
    REFERENCES `sanjosep_ventas`.`pagos` (`tipo_pago`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`devolucion` (
  `id_devolucion` INT(20) NOT NULL,
  `id_ticket` INT(20) NOT NULL,
  `upc` VARCHAR(20) NULL,
  `sku` INT(10) NOT NULL,
  `piezas` FLOAT(10,4) NOT NULL,
  `comentario` VARCHAR(100) NULL,
  `usuario_creacion` VARCHAR(20) NULL,
  `usuario_autoriza` VARCHAR(20) NULL,
  `fecha_autoriza` DATETIME NULL,
  PRIMARY KEY (`id_devolucion`, `sku`),
  INDEX `fk_devolucion_transaccion_venta1_idx` (`id_ticket` ASC),
  CONSTRAINT `fk_devolucion_transaccion_venta1`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `sanjosep_ventas`.`transaccion_venta` (`no_ticket`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`inicio_sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`inicio_sesion` (
  `id_inicio_user` INT(20) NOT NULL,
  `usuario_inicio` VARCHAR(20) NOT NULL,
  `estatus` VARCHAR(4) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_cierre` DATETIME NULL,
  PRIMARY KEY (`id_inicio_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`fondo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`fondo` (
  `id_inicio_user` INT(20) NOT NULL,
  `denominacion` INT(4) NOT NULL,
  `total` INT(4) NOT NULL,
  `monto_total` FLOAT(10,4) NOT NULL,
  CONSTRAINT `fk_fondo_inicio_sesion1`
    FOREIGN KEY (`id_inicio_user`)
    REFERENCES `sanjosep_ventas`.`inicio_sesion` (`id_inicio_user`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`entradas_salidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`entradas_salidas` (
  `id_entrada` INT(20) NOT NULL,
  `total` FLOAT(10,4) NOT NULL,
  `razon` VARCHAR(200) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `Usuario_creacion` VARCHAR(20) NOT NULL,
  `id_inicio_user` INT(20) NOT NULL,
  PRIMARY KEY (`id_entrada`, `id_inicio_user`),
  INDEX `fk_entradas_salidas_inicio_sesion1_idx` (`id_inicio_user` ASC),
  CONSTRAINT `fk_entradas_salidas_inicio_sesion1`
    FOREIGN KEY (`id_inicio_user`)
    REFERENCES `sanjosep_ventas`.`inicio_sesion` (`id_inicio_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`lista_precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`lista_precio` (
  `id_lista` INT(20) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  `Usuario_creacion` DATETIME NULL,
  PRIMARY KEY (`id_lista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`lista_preceio_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`lista_preceio_detalle` (
  `id_lista` INT(20) NOT NULL,
  `sku` VARCHAR(15) NOT NULL,
  `precio` FLOAT(10,4) NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(20) NULL,
  PRIMARY KEY (`id_lista`, `sku`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`promociones` (
  `id_promocion` INT(20) NOT NULL,
  `desccripcion` VARCHAR(50) NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(20) NULL,
  `estatus` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_promocion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanjosep_ventas`.`promocion_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`promocion_detalle` (
  `id_promocion` INT(20) NOT NULL,
  `sku` VARCHAR(10) NULL,
  `precio` FLOAT(10,4) NULL,
  `minimo` FLOAT(10,4) NULL,
  `maximo` FLOAT(10,4) NULL,
  `tipo_prom` VARCHAR(10) NULL,
  `porcentaje` FLOAT(10,4) NULL,
  `monto` FLOAT(10,4) NULL,
  `paquete` VARCHAR(10) NULL,
  PRIMARY KEY (`id_promocion`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `sanjosep_ventas`.`usuario` (
  `id_usuario` INT(20) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(40) NOT NULL,
  `apellido_materno` VARCHAR(40) NOT NULL,
  `puesto` INT(10) NOT NULL,
  `permiso` INT(10) NOT NULL,
  `tienda_cd` INT(4) NULL,
  `password` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
